# Numpy in Python for DS

Main component of scientific computing in Python. This library helps us to implement linear algebra in Python. 

In [1]:
!pip install numpy

In [2]:
import numpy
numpy.__version__

'1.24.2'

## Basics

In [3]:
import numpy as np
a_1d_vector = np.array([1, 2, 3])
a_row_vector = np.array([[1, 2, 3]])
a_column_vector = np.array([[1], [2], [3]])
a_2d_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
    ])

In [27]:
type(a_1d_vector)

numpy.ndarray

In [4]:
print(a_1d_vector.shape)
print(a_row_vector.shape)
print(a_column_vector.shape)
print(a_2d_matrix.shape)

(3,)
(1, 3)
(3, 1)
(2, 3)


In [9]:
random_matrix = np.random.rand(30, 30)

In [10]:
print(random_matrix)

[[0.38921285 0.12342041 0.49565367 0.35970263 0.71730313 0.01900279
  0.15651087 0.95604781 0.22351413 0.96385752 0.43256788 0.04243795
  0.30071333 0.26935427 0.49310715 0.29541195 0.9719887  0.41534287
  0.48898381 0.2988366  0.92095371 0.05100016 0.16007964 0.28853071
  0.79046732 0.84622447 0.71179606 0.96959835 0.23035005 0.46755305]
 [0.30840432 0.13029664 0.24262256 0.97902216 0.791214   0.87510078
  0.2749572  0.4494435  0.3736423  0.86478387 0.39446396 0.97369987
  0.08262937 0.93690642 0.16584961 0.85127036 0.12734308 0.03482573
  0.21104293 0.1821866  0.56050305 0.50453115 0.47734811 0.56252824
  0.42905545 0.19030936 0.10790273 0.05561882 0.87776617 0.57865822]
 [0.92687926 0.17832864 0.25732635 0.09942725 0.50448103 0.74104797
  0.57525326 0.95774803 0.42863438 0.82916566 0.59823647 0.65534226
  0.77404215 0.01423103 0.25915422 0.73527331 0.37688536 0.09821653
  0.91980673 0.08439376 0.72259769 0.74680136 0.09263116 0.58165431
  0.34477166 0.03754116 0.59913761 0.21158261 

In [11]:
random_matrix[3, 5]

0.834222560309068

In [124]:
random_matrix[3]

array([0.75059168, 0.11014011, 0.84860185, 0.67450341, 0.21025977,
       0.50340844, 0.04855257, 0.81504576, 0.02671449, 0.74308264,
       0.06849829, 0.14462425, 0.12297315, 0.99436337, 0.6315172 ,
       0.76824108, 0.62777428, 0.6735005 , 0.1672391 , 0.20753785,
       0.54854948, 0.48647827, 0.93658536, 0.88793968, 0.46553205,
       0.78460994, 0.7842312 , 0.23266832, 0.65368229, 0.02928088])

In [14]:
alist = [1, 2, 3]
alist[1:3]

[2, 3]

In [17]:
random_matrix[:, 5]

array([0.01900279, 0.87510078, 0.74104797, 0.83422256, 0.07380898,
       0.46146908, 0.27826949, 0.48126682, 0.96607755, 0.32986421,
       0.15321576, 0.74928101, 0.79222458, 0.9186312 , 0.78559334,
       0.83855144, 0.32795757, 0.29755315, 0.11520317, 0.07290727,
       0.26749255, 0.42672258, 0.41291325, 0.07055888, 0.10369769,
       0.70068139, 0.79416062, 0.27932505, 0.1959871 , 0.42119843])

In [18]:
random_matrix[2:5, 5]

array([0.74104797, 0.83422256, 0.07380898])

In [19]:
random_matrix[3, 4:7]

array([0.53995515, 0.83422256, 0.8083053 ])

In [130]:
random_matrix[2:5, 4:7]

array([[0.24798638, 0.27515681, 0.12688929],
       [0.21025977, 0.50340844, 0.04855257],
       [0.33489053, 0.09521122, 0.59688064]])

In [35]:
a_zero_matrix = np.zeros((2, 3), dtype=np.int8)
print(a_zero_matrix)

[[0 0 0]
 [0 0 0]]


In [22]:
a_zero_matrix[0, 1] = 1
print(a_zero_matrix)

[[0 1 0]
 [0 0 0]]


In [24]:
a_zero_matrix[0, 1] = 1.2
print(a_zero_matrix)
print(a_zero_matrix.dtype)

[[0 1 0]
 [0 0 0]]
int8


In [25]:
a_zero_matrix[0, 1] = 275
print(a_zero_matrix)
print(a_zero_matrix.dtype)

[[ 0 19  0]
 [ 0  0  0]]
int8


/var/folders/rg/r1h2qhf502n6zsj0xdv9t3cw0000gn/T/ipykernel_95051/358024267.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 275 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a_zero_matrix[0, 1] = 275


In [26]:
a_ones_matrix = np.ones((2, 3))
a_diagonal_matrix = np.eye(3)
print(a_diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
a_row_vector + a_column_vector

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [31]:
a_row_vector + a_column_vector.T

array([[2, 4, 6]])

In [36]:
a_zero_matrix

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [37]:
np.multiply(a_2d_matrix, a_zero_matrix)

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
a_2d_matrix * a_ones_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
a_2d_matrix + a_diagonal_matrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [39]:
a_2d_matrix * a_diagonal_matrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [41]:
np.matmul(a_2d_matrix, a_diagonal_matrix)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
np.matmul(a_2d_matrix, a_ones_matrix)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [46]:
a_2d_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.matmul(a_2d_matrix, a_ones_matrix.T)

array([[ 6.,  6.],
       [15., 15.]])

In [73]:
np.matmul(a_row_vector, a_column_vector)

array([[14]])

In [74]:
np.matmul(a_column_vector, a_row_vector)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [47]:
print(a_2d_matrix)
np.sum(a_2d_matrix, axis=0) # sum of columns

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [99]:
np.sum(a_2d_matrix, axis=1) # sum of rows

array([ 6, 15])

In [48]:
np.sum(a_2d_matrix)

21

In [100]:
np.max(a_2d_matrix, axis=0) # max of columns

array([4, 5, 6])

In [104]:
np.mean(a_2d_matrix, axis=0) # mean of columnsb

array([2.5, 3.5, 4.5])

In [105]:
np.mean(a_2d_matrix)

3.5

Linear combinations - solver

3x + 2y = 9
5x + 23y = 15
What are x and y?


In [50]:
A = np.matrix([
    [3,2],
    [5,23]
])
y = np.matrix([
    [9], 
    [15]
])

In [51]:
x = np.linalg.solve(A, y)
print(x)

[[3.00000000e+00]
 [1.12904036e-16]]
