# Numpy in Python for DS

Main component of scientific computing in Python. This library helps us to implement linear algebra in Python. 

In [1]:
!pip install numpy

## Basics

In [66]:
import numpy as np
a_1d_vector = np.array([1, 2, 3])
a_row_vector = np.array([[1, 2, 3]])
a_column_vector = np.array([
    [1], 
    [2], 
    [3]
    ])
a_2d_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
    ])

In [67]:
print(a_1d_vector.shape)
print(a_row_vector.shape)
print(a_column_vector.shape)
print(a_2d_matrix.shape)

(3,)
(1, 3)
(3, 1)
(2, 3)


In [118]:
random_matrix = np.random.rand(30, 30)

In [119]:
random_matrix[3, 5]

0.5034084436202085

In [124]:
random_matrix[3]

array([0.75059168, 0.11014011, 0.84860185, 0.67450341, 0.21025977,
       0.50340844, 0.04855257, 0.81504576, 0.02671449, 0.74308264,
       0.06849829, 0.14462425, 0.12297315, 0.99436337, 0.6315172 ,
       0.76824108, 0.62777428, 0.6735005 , 0.1672391 , 0.20753785,
       0.54854948, 0.48647827, 0.93658536, 0.88793968, 0.46553205,
       0.78460994, 0.7842312 , 0.23266832, 0.65368229, 0.02928088])

In [125]:
random_matrix[:, 5]

array([0.80179893, 0.10688911, 0.27515681, 0.50340844, 0.09521122,
       0.84966902, 0.65973787, 0.48297187, 0.83874901, 0.56864953,
       0.65481667, 0.99731042, 0.7205876 , 0.24745005, 0.09574269,
       0.85651902, 0.23789431, 0.28167235, 0.50113687, 0.55747654,
       0.11589226, 0.39875029, 0.07729785, 0.57899385, 0.65703628,
       0.19115198, 0.02842407, 0.56585523, 0.07224997, 0.79241144])

In [127]:
random_matrix[2:5, 5]

array([0.27515681, 0.50340844, 0.09521122])

In [129]:
random_matrix[3, 4:7]

array([0.21025977, 0.50340844, 0.04855257])

In [130]:
random_matrix[2:5, 4:7]

array([[0.24798638, 0.27515681, 0.12688929],
       [0.21025977, 0.50340844, 0.04855257],
       [0.33489053, 0.09521122, 0.59688064]])

In [82]:
a_zero_matrix = np.zeros((2, 3))
print(a_zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [84]:
a_ones_matrix = np.ones((2, 3))
a_diagonal_matrix = np.eye(3)
print(a_diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
a_row_vector + a_column_vector.T

array([[2, 4, 6]])

In [85]:
np.multiply(a_2d_matrix, a_zero_matrix)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
a_2d_matrix * a_ones_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [87]:
a_2d_matrix * a_diagonal_matrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [94]:
np.matmul(a_2d_matrix, a_diagonal_matrix)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [96]:
np.matmul(a_2d_matrix, a_ones_matrix)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [97]:
np.matmul(a_2d_matrix, a_ones_matrix.T)

array([[ 6.,  6.],
       [15., 15.]])

In [73]:
np.matmul(a_row_vector, a_column_vector)

array([[14]])

In [74]:
np.matmul(a_column_vector, a_row_vector)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [98]:
np.sum(a_2d_matrix, axis=0) # sum of columns

array([5, 7, 9])

In [99]:
np.sum(a_2d_matrix, axis=1) # sum of rows

array([ 6, 15])

In [100]:
np.max(a_2d_matrix, axis=0) # max of columns

array([4, 5, 6])

In [104]:
np.mean(a_2d_matrix, axis=0) # mean of columnsb

array([2.5, 3.5, 4.5])

In [105]:
np.mean(a_2d_matrix)

3.5

Linear combinations - solver

3x + 2y = 9
5x + 23y = 15
What are x and y?


In [101]:
A = np.matrix([
    [3,2],
    [5,23]
])
y = np.matrix([
    [9], 
    [15]
])

In [103]:
x = np.linalg.solve(A, y)
print(x)

[[3.00000000e+00]
 [1.12904036e-16]]
